// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98kt2yysBifCfCTTgfX14tNPUuxtheY0',
    appId: '1:1092788065466:android:8b923c4208f1e11d1a5e83',
    messagingSenderId: '1092788065466',
    projectId: 'proyecto-paseando-mascotas1',
    storageBucket: 'proyecto-paseando-mascotas1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWzWhc4AmUqdr5p5fqSHgRhkxl0AD9Us4',
    appId: '1:1092788065466:ios:12fc23a310eb5a441a5e83',
    messagingSenderId: '1092788065466',
    projectId: 'proyecto-paseando-mascotas1',
    storageBucket: 'proyecto-paseando-mascotas1.appspot.com',
    iosClientId: '1092788065466-15dshhnfqhchqva1n71ba9vpu77013er.apps.googleusercontent.com',
    iosBundleId: 'com.example.paseadorMascotas',
  );
}
